FALLBACK_TOOLS = [
    {
        'id': 'github-copilot',
        'name': 'GitHub Copilot',
        'category': 'Coding',
        'description': 'AI pair programmer for code suggestions and chat',
        'url': 'https://github.com/features/copilot',
        'pricing': 'Free + Paid',
        'score': 97,
        'developer': 'Microsoft/GitHub',
        'trending': True,
        'tags': ['ai', 'coding', 'code', 'development', 'programming'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 92, 'speed': 95, 'ease': 97, 'value': 94},
    },
    {
        'id': 'codeium',
        'name': 'Codeium',
        'category': 'Coding',
        'description': 'Free AI coding assistant with broad language support',
        'url': 'https://codeium.com',
        'pricing': 'Free + Paid',
        'score': 85,
        'developer': 'Exafunction',
        'trending': False,
        'tags': ['ai', 'coding', 'code', 'development', 'programming'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 80, 'speed': 83, 'ease': 85, 'value': 82},
    },
    {
        'id': 'tabnine',
        'name': 'Tabnine',
        'category': 'Coding',
        'description': 'AI code completion powered by deep learning',
        'url': 'https://www.tabnine.com',
        'pricing': 'Free + Paid',
        'score': 84,
        'developer': 'Tabnine',
        'trending': False,
        'tags': ['ai', 'coding', 'code', 'development', 'programming'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 79, 'speed': 82, 'ease': 84, 'value': 81},
    },
    {
        'id': 'claude',
        'name': 'Claude',
        'category': 'Coding',
        'description': 'Advanced AI assistant for coding and analysis',
        'url': 'https://claude.ai',
        'pricing': 'Free + Paid',
        'score': 96,
        'developer': 'Anthropic',
        'trending': False,
        'tags': ['ai', 'coding', 'code', 'development', 'programming'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 91, 'speed': 94, 'ease': 96, 'value': 93},
    },
    {
        'id': 'codex',
        'name': 'Codex',
        'category': 'Coding',
        'description': 'OpenAI's code generation model',
        'url': 'https://openai.com/codex',
        'pricing': 'Free + Paid',
        'score': 89,
        'developer': 'OpenAI',
        'trending': False,
        'tags': ['ai', 'coding', 'code', 'development', 'programming'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 84, 'speed': 87, 'ease': 89, 'value': 86},
    },
    {
        'id': 'replit-ghostwriter',
        'name': 'Replit Ghostwriter',
        'category': 'Coding',
        'description': 'AI coding assistant in Replit IDE',
        'url': 'https://replit.com',
        'pricing': 'Free + Paid',
        'score': 82,
        'developer': 'Replit',
        'trending': True,
        'tags': ['ai', 'coding', 'code', 'development', 'programming'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 77, 'speed': 80, 'ease': 82, 'value': 79},
    },
    {
        'id': 'amazon-codewhisperer',
        'name': 'Amazon CodeWhisperer',
        'category': 'Coding',
        'description': 'ML-powered code suggestions by AWS',
        'url': 'https://aws.amazon.com/codewhisperer',
        'pricing': 'Free + Paid',
        'score': 83,
        'developer': 'Amazon',
        'trending': False,
        'tags': ['ai', 'coding', 'code', 'development', 'programming'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 78, 'speed': 81, 'ease': 83, 'value': 80},
    },
    {
        'id': 'perplexity-ai',
        'name': 'Perplexity AI',
        'category': 'Coding',
        'description': 'AI assistant for research and coding',
        'url': 'https://perplexity.ai',
        'pricing': 'Free + Paid',
        'score': 88,
        'developer': 'Perplexity',
        'trending': True,
        'tags': ['ai', 'coding', 'code', 'development', 'programming'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 83, 'speed': 86, 'ease': 88, 'value': 85},
    },
    {
        'id': 'chatgpt',
        'name': 'ChatGPT',
        'category': 'Writing',
        'description': 'Advanced general-purpose AI assistant',
        'url': 'https://chatgpt.com',
        'pricing': 'Free + Paid',
        'score': 98,
        'developer': 'OpenAI',
        'trending': False,
        'tags': ['ai', 'writing', 'writing', 'content', 'marketing'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 93, 'speed': 96, 'ease': 98, 'value': 95},
    },
    {
        'id': 'jasper',
        'name': 'Jasper',
        'category': 'Writing',
        'description': 'AI content writer for marketers',
        'url': 'https://www.jasper.ai',
        'pricing': 'Free + Paid',
        'score': 87,
        'developer': 'Jasper',
        'trending': True,
        'tags': ['ai', 'writing', 'writing', 'content', 'marketing'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 82, 'speed': 85, 'ease': 87, 'value': 84},
    },
    {
        'id': 'copy-ai',
        'name': 'Copy.ai',
        'category': 'Writing',
        'description': 'AI copywriting tool for marketing',
        'url': 'https://www.copy.ai',
        'pricing': 'Free + Paid',
        'score': 84,
        'developer': 'Copy.ai',
        'trending': False,
        'tags': ['ai', 'writing', 'writing', 'content', 'marketing'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 79, 'speed': 82, 'ease': 84, 'value': 81},
    },
    {
        'id': 'writersonic',
        'name': 'Writersonic',
        'category': 'Writing',
        'description': 'AI writer for content creation',
        'url': 'https://writersonic.com',
        'pricing': 'Free + Paid',
        'score': 83,
        'developer': 'Writersonic',
        'trending': True,
        'tags': ['ai', 'writing', 'writing', 'content', 'marketing'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 78, 'speed': 81, 'ease': 83, 'value': 80},
    },
    {
        'id': 'grammarly',
        'name': 'Grammarly',
        'category': 'Writing',
        'description': 'AI-powered writing assistant',
        'url': 'https://www.grammarly.com',
        'pricing': 'Free + Paid',
        'score': 92,
        'developer': 'Grammarly',
        'trending': False,
        'tags': ['ai', 'writing', 'writing', 'content', 'marketing'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 87, 'speed': 90, 'ease': 92, 'value': 89},
    },
    {
        'id': 'hemingway-editor',
        'name': 'Hemingway Editor',
        'category': 'Writing',
        'description': 'App to improve writing clarity',
        'url': 'https://www.hemingwayapp.com',
        'pricing': 'Free + Paid',
        'score': 80,
        'developer': 'Hemingway',
        'trending': False,
        'tags': ['ai', 'writing', 'writing', 'content', 'marketing'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 75, 'speed': 78, 'ease': 80, 'value': 77},
    },
    {
        'id': 'quillbot',
        'name': 'Quillbot',
        'category': 'Writing',
        'description': 'AI paraphrasing and writing tool',
        'url': 'https://quillbot.com',
        'pricing': 'Free + Paid',
        'score': 85,
        'developer': 'QuillBot',
        'trending': True,
        'tags': ['ai', 'writing', 'writing', 'content', 'marketing'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 80, 'speed': 83, 'ease': 85, 'value': 82},
    },
    {
        'id': 'prowritingaid',
        'name': 'ProWritingAid',
        'category': 'Writing',
        'description': 'Writing analysis and improvement tool',
        'url': 'https://www.prowritingaid.com',
        'pricing': 'Free + Paid',
        'score': 88,
        'developer': 'ProWritingAid',
        'trending': True,
        'tags': ['ai', 'writing', 'writing', 'content', 'marketing'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 83, 'speed': 86, 'ease': 88, 'value': 85},
    },
    {
        'id': 'sudowrite',
        'name': 'Sudowrite',
        'category': 'Writing',
        'description': 'AI writing assistant for creative writers',
        'url': 'https://www.sudowrite.com',
        'pricing': 'Free + Paid',
        'score': 86,
        'developer': 'Sudowrite',
        'trending': True,
        'tags': ['ai', 'writing', 'writing', 'content', 'marketing'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 81, 'speed': 84, 'ease': 86, 'value': 83},
    },
    {
        'id': 'midjourney',
        'name': 'Midjourney',
        'category': 'Design',
        'description': 'AI image generator for creative prompts',
        'url': 'https://www.midjourney.com',
        'pricing': 'Free + Paid',
        'score': 94,
        'developer': 'Midjourney',
        'trending': True,
        'tags': ['ai', 'design', 'design', 'image', 'creative', 'generation'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 89, 'speed': 92, 'ease': 94, 'value': 91},
    },
    {
        'id': 'dall-e',
        'name': 'DALL-E',
        'category': 'Design',
        'description': 'OpenAI's AI image generation model',
        'url': 'https://openai.com/dall-e-3',
        'pricing': 'Free + Paid',
        'score': 93,
        'developer': 'OpenAI',
        'trending': True,
        'tags': ['ai', 'design', 'design', 'image', 'creative', 'generation'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 88, 'speed': 91, 'ease': 93, 'value': 90},
    },
    {
        'id': 'stable-diffusion',
        'name': 'Stable Diffusion',
        'category': 'Design',
        'description': 'Open-source AI image generation',
        'url': 'https://stability.ai',
        'pricing': 'Free + Paid',
        'score': 91,
        'developer': 'Stability AI',
        'trending': True,
        'tags': ['ai', 'design', 'design', 'image', 'creative', 'generation'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 86, 'speed': 89, 'ease': 91, 'value': 88},
    },
    {
        'id': 'adobe-firefly',
        'name': 'Adobe Firefly',
        'category': 'Design',
        'description': 'AI generative features in Adobe products',
        'url': 'https://www.adobe.com/firefly',
        'pricing': 'Free + Paid',
        'score': 89,
        'developer': 'Adobe',
        'trending': False,
        'tags': ['ai', 'design', 'design', 'image', 'creative', 'generation'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 84, 'speed': 87, 'ease': 89, 'value': 86},
    },
    {
        'id': 'canva-ai',
        'name': 'Canva AI',
        'category': 'Design',
        'description': 'AI-powered design suggestions in Canva',
        'url': 'https://www.canva.com',
        'pricing': 'Free + Paid',
        'score': 86,
        'developer': 'Canva',
        'trending': True,
        'tags': ['ai', 'design', 'design', 'image', 'creative', 'generation'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 81, 'speed': 84, 'ease': 86, 'value': 83},
    },
    {
        'id': 'figma-ai',
        'name': 'Figma AI',
        'category': 'Design',
        'description': 'AI design tools in Figma',
        'url': 'https://www.figma.com',
        'pricing': 'Free + Paid',
        'score': 87,
        'developer': 'Figma',
        'trending': True,
        'tags': ['ai', 'design', 'design', 'image', 'creative', 'generation'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 82, 'speed': 85, 'ease': 87, 'value': 84},
    },
    {
        'id': 'runway',
        'name': 'Runway',
        'category': 'Design',
        'description': 'AI video and image generation platform',
        'url': 'https://www.runway.com',
        'pricing': 'Free + Paid',
        'score': 88,
        'developer': 'Runway ML',
        'trending': True,
        'tags': ['ai', 'design', 'design', 'image', 'creative', 'generation'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 83, 'speed': 86, 'ease': 88, 'value': 85},
    },
    {
        'id': 'synthesia',
        'name': 'Synthesia',
        'category': 'Design',
        'description': 'AI video generation from text',
        'url': 'https://www.synthesia.io',
        'pricing': 'Free + Paid',
        'score': 85,
        'developer': 'Synthesia',
        'trending': True,
        'tags': ['ai', 'design', 'design', 'image', 'creative', 'generation'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 80, 'speed': 83, 'ease': 85, 'value': 82},
    },
    {
        'id': 'd-id',
        'name': 'D-ID',
        'category': 'Design',
        'description': 'AI video generation with digital avatars',
        'url': 'https://www.d-id.com',
        'pricing': 'Free + Paid',
        'score': 83,
        'developer': 'D-ID',
        'trending': False,
        'tags': ['ai', 'design', 'design', 'image', 'creative', 'generation'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 78, 'speed': 81, 'ease': 83, 'value': 80},
    },
    {
        'id': 'zapier',
        'name': 'Zapier',
        'category': 'Automation',
        'description': 'Workflow automation and integrations',
        'url': 'https://zapier.com',
        'pricing': 'Free + Paid',
        'score': 90,
        'developer': 'Zapier',
        'trending': True,
        'tags': ['ai', 'automation', 'automation', 'workflow', 'integration'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 85, 'speed': 88, 'ease': 90, 'value': 87},
    },
    {
        'id': 'n8n',
        'name': 'n8n',
        'category': 'Automation',
        'description': 'Open-source workflow automation platform',
        'url': 'https://n8n.io',
        'pricing': 'Free + Paid',
        'score': 88,
        'developer': 'n8n',
        'trending': True,
        'tags': ['ai', 'automation', 'automation', 'workflow', 'integration'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 83, 'speed': 86, 'ease': 88, 'value': 85},
    },
    {
        'id': 'make',
        'name': 'Make (Integromat)',
        'category': 'Automation',
        'description': 'Cloud automation and workflow platform',
        'url': 'https://www.make.com',
        'pricing': 'Free + Paid',
        'score': 87,
        'developer': 'Make',
        'trending': True,
        'tags': ['ai', 'automation', 'automation', 'workflow', 'integration'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 82, 'speed': 85, 'ease': 87, 'value': 84},
    },
    {
        'id': 'ifttt',
        'name': 'IFTTT',
        'category': 'Automation',
        'description': 'If This Then That automation service',
        'url': 'https://ifttt.com',
        'pricing': 'Free + Paid',
        'score': 82,
        'developer': 'IFTTT',
        'trending': True,
        'tags': ['ai', 'automation', 'automation', 'workflow', 'integration'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 77, 'speed': 80, 'ease': 82, 'value': 79},
    },
    {
        'id': 'automation-anywhere',
        'name': 'Automation Anywhere',
        'category': 'Automation',
        'description': 'Enterprise RPA platform',
        'url': 'https://www.automationanywhere.com',
        'pricing': 'Free + Paid',
        'score': 85,
        'developer': 'Automation Anywhere',
        'trending': False,
        'tags': ['ai', 'automation', 'automation', 'workflow', 'integration'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 80, 'speed': 83, 'ease': 85, 'value': 82},
    },
    {
        'id': 'uipath',
        'name': 'UiPath',
        'category': 'Automation',
        'description': 'Enterprise robotic process automation',
        'url': 'https://www.uipath.com',
        'pricing': 'Free + Paid',
        'score': 86,
        'developer': 'UiPath',
        'trending': False,
        'tags': ['ai', 'automation', 'automation', 'workflow', 'integration'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 81, 'speed': 84, 'ease': 86, 'value': 83},
    },
    {
        'id': 'assistant',
        'name': 'Assistant',
        'category': 'Automation',
        'description': 'AI automation assistant for repetitive tasks',
        'url': 'https://example.com',
        'pricing': 'Free + Paid',
        'score': 80,
        'developer': 'Various',
        'trending': True,
        'tags': ['ai', 'automation', 'automation', 'workflow', 'integration'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 75, 'speed': 78, 'ease': 80, 'value': 77},
    },
    {
        'id': 'power-bi',
        'name': 'Power BI',
        'category': 'Business',
        'description': 'Business analytics and data visualization',
        'url': 'https://powerbi.microsoft.com',
        'pricing': 'Free + Paid',
        'score': 89,
        'developer': 'Microsoft',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 84, 'speed': 87, 'ease': 89, 'value': 86},
    },
    {
        'id': 'tableau',
        'name': 'Tableau',
        'category': 'Business',
        'description': 'Data visualization and analytics platform',
        'url': 'https://www.tableau.com',
        'pricing': 'Free + Paid',
        'score': 90,
        'developer': 'Salesforce',
        'trending': False,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 85, 'speed': 88, 'ease': 90, 'value': 87},
    },
    {
        'id': 'looker',
        'name': 'Looker',
        'category': 'Business',
        'description': 'Business intelligence and analytics',
        'url': 'https://www.looker.com',
        'pricing': 'Free + Paid',
        'score': 88,
        'developer': 'Google',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 83, 'speed': 86, 'ease': 88, 'value': 85},
    },
    {
        'id': 'alteryx',
        'name': 'Alteryx',
        'category': 'Business',
        'description': 'Data analytics and automation platform',
        'url': 'https://www.alteryx.com',
        'pricing': 'Free + Paid',
        'score': 85,
        'developer': 'Alteryx',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 80, 'speed': 83, 'ease': 85, 'value': 82},
    },
    {
        'id': 'qlik',
        'name': 'Qlik',
        'category': 'Business',
        'description': 'Data analytics and visualization platform',
        'url': 'https://www.qlik.com',
        'pricing': 'Free + Paid',
        'score': 86,
        'developer': 'Qlik',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 81, 'speed': 84, 'ease': 86, 'value': 83},
    },
    {
        'id': 'scale-ai',
        'name': 'Scale AI',
        'category': 'Business',
        'description': 'Data labeling and quality for AI',
        'url': 'https://www.scale.com',
        'pricing': 'Free + Paid',
        'score': 87,
        'developer': 'Scale AI',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 82, 'speed': 85, 'ease': 87, 'value': 84},
    },
    {
        'id': 'consensus',
        'name': 'Consensus',
        'category': 'Research',
        'description': 'AI research paper search engine',
        'url': 'https://consensus.app',
        'pricing': 'Free + Paid',
        'score': 84,
        'developer': 'Consensus',
        'trending': True,
        'tags': ['ai', 'research', 'research', 'learning', 'education'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 79, 'speed': 82, 'ease': 84, 'value': 81},
    },
    {
        'id': 'semantic-scholar',
        'name': 'Semantic Scholar',
        'category': 'Research',
        'description': 'AI-powered academic paper search',
        'url': 'https://www.semanticscholar.org',
        'pricing': 'Free + Paid',
        'score': 86,
        'developer': 'Allen AI',
        'trending': False,
        'tags': ['ai', 'research', 'research', 'learning', 'education'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 81, 'speed': 84, 'ease': 86, 'value': 83},
    },
    {
        'id': 'scholarcy',
        'name': 'Scholarcy',
        'category': 'Research',
        'description': 'AI summarization of research papers',
        'url': 'https://www.scholarcy.com',
        'pricing': 'Free + Paid',
        'score': 82,
        'developer': 'Scholarcy',
        'trending': True,
        'tags': ['ai', 'research', 'research', 'learning', 'education'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 77, 'speed': 80, 'ease': 82, 'value': 79},
    },
    {
        'id': 'paperswithcode',
        'name': 'PapersWithCode',
        'category': 'Research',
        'description': 'ML research papers with code',
        'url': 'https://www.paperswithcode.com',
        'pricing': 'Free + Paid',
        'score': 88,
        'developer': 'Meta',
        'trending': False,
        'tags': ['ai', 'research', 'research', 'learning', 'education'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 83, 'speed': 86, 'ease': 88, 'value': 85},
    },
    {
        'id': 'dimensions',
        'name': 'Dimensions',
        'category': 'Research',
        'description': 'Research analytics and discovery platform',
        'url': 'https://www.dimensions.ai',
        'pricing': 'Free + Paid',
        'score': 85,
        'developer': 'Dimensions',
        'trending': True,
        'tags': ['ai', 'research', 'research', 'learning', 'education'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 80, 'speed': 83, 'ease': 85, 'value': 82},
    },
    {
        'id': 'elevenlabs',
        'name': 'ElevenLabs',
        'category': 'Voice',
        'description': 'AI voice generation and synthesis',
        'url': 'https://elevenlabs.io',
        'pricing': 'Free + Paid',
        'score': 91,
        'developer': 'ElevenLabs',
        'trending': True,
        'tags': ['ai', 'voice', 'voice', 'audio', 'speech', 'transcription'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 86, 'speed': 89, 'ease': 91, 'value': 88},
    },
    {
        'id': 'descript',
        'name': 'Descript',
        'category': 'Voice',
        'description': 'Video and audio editing with AI',
        'url': 'https://www.descript.com',
        'pricing': 'Free + Paid',
        'score': 88,
        'developer': 'Descript',
        'trending': False,
        'tags': ['ai', 'voice', 'voice', 'audio', 'speech', 'transcription'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 83, 'speed': 86, 'ease': 88, 'value': 85},
    },
    {
        'id': 'otter-ai',
        'name': 'Otter.ai',
        'category': 'Voice',
        'description': 'AI transcription and meeting notes',
        'url': 'https://otter.ai',
        'pricing': 'Free + Paid',
        'score': 86,
        'developer': 'Otter',
        'trending': False,
        'tags': ['ai', 'voice', 'voice', 'audio', 'speech', 'transcription'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 81, 'speed': 84, 'ease': 86, 'value': 83},
    },
    {
        'id': 'fireflies-ai',
        'name': 'Fireflies.ai',
        'category': 'Voice',
        'description': 'AI meeting recording and transcription',
        'url': 'https://fireflies.ai',
        'pricing': 'Free + Paid',
        'score': 84,
        'developer': 'Fireflies',
        'trending': True,
        'tags': ['ai', 'voice', 'voice', 'audio', 'speech', 'transcription'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 79, 'speed': 82, 'ease': 84, 'value': 81},
    },
    {
        'id': 'rev',
        'name': 'Rev',
        'category': 'Voice',
        'description': 'Professional transcription services',
        'url': 'https://www.rev.com',
        'pricing': 'Free + Paid',
        'score': 83,
        'developer': 'Rev',
        'trending': True,
        'tags': ['ai', 'voice', 'voice', 'audio', 'speech', 'transcription'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 78, 'speed': 81, 'ease': 83, 'value': 80},
    },
    {
        'id': 'murf-ai',
        'name': 'Murf AI',
        'category': 'Voice',
        'description': 'Text-to-speech with AI voices',
        'url': 'https://murf.ai',
        'pricing': 'Free + Paid',
        'score': 85,
        'developer': 'Murf',
        'trending': False,
        'tags': ['ai', 'voice', 'voice', 'audio', 'speech', 'transcription'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 80, 'speed': 83, 'ease': 85, 'value': 82},
    },
    {
        'id': 'google-cloud-speech',
        'name': 'Google Cloud Speech',
        'category': 'Voice',
        'description': 'Google's speech recognition API',
        'url': 'https://cloud.google.com/speech-to-text',
        'pricing': 'Free + Paid',
        'score': 89,
        'developer': 'Google',
        'trending': True,
        'tags': ['ai', 'voice', 'voice', 'audio', 'speech', 'transcription'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 84, 'speed': 87, 'ease': 89, 'value': 86},
    },
    {
        'id': 'fliki',
        'name': 'Fliki',
        'category': 'Design',
        'description': 'AI video creation from text and images',
        'url': 'https://fliki.ai',
        'pricing': 'Free + Paid',
        'score': 83,
        'developer': 'Fliki',
        'trending': True,
        'tags': ['ai', 'design', 'design', 'image', 'creative', 'generation'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 78, 'speed': 81, 'ease': 83, 'value': 80},
    },
    {
        'id': 'pictory',
        'name': 'Pictory',
        'category': 'Design',
        'description': 'AI video generation from scripts',
        'url': 'https://www.pictory.ai',
        'pricing': 'Free + Paid',
        'score': 82,
        'developer': 'Pictory',
        'trending': True,
        'tags': ['ai', 'design', 'design', 'image', 'creative', 'generation'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 77, 'speed': 80, 'ease': 82, 'value': 79},
    },
    {
        'id': 'heygen',
        'name': 'HeyGen',
        'category': 'Design',
        'description': 'AI video generator with avatars',
        'url': 'https://www.heygen.com',
        'pricing': 'Free + Paid',
        'score': 84,
        'developer': 'HeyGen',
        'trending': True,
        'tags': ['ai', 'design', 'design', 'image', 'creative', 'generation'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 79, 'speed': 82, 'ease': 84, 'value': 81},
    },
    {
        'id': 'opusclip',
        'name': 'OpusClip',
        'category': 'Design',
        'description': 'AI short-form video creation',
        'url': 'https://opusclip.com',
        'pricing': 'Free + Paid',
        'score': 81,
        'developer': 'OpusClip',
        'trending': False,
        'tags': ['ai', 'design', 'design', 'image', 'creative', 'generation'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 76, 'speed': 79, 'ease': 81, 'value': 78},
    },
    {
        'id': 'runway-gen2',
        'name': 'Runway Gen-2',
        'category': 'Design',
        'description': 'AI video generation model',
        'url': 'https://www.runway.com',
        'pricing': 'Free + Paid',
        'score': 87,
        'developer': 'Runway',
        'trending': True,
        'tags': ['ai', 'design', 'design', 'image', 'creative', 'generation'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 82, 'speed': 85, 'ease': 87, 'value': 84},
    },
    {
        'id': 'intercom',
        'name': 'Intercom',
        'category': 'Business',
        'description': 'Customer communication platform with AI',
        'url': 'https://www.intercom.com',
        'pricing': 'Free + Paid',
        'score': 85,
        'developer': 'Intercom',
        'trending': False,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 80, 'speed': 83, 'ease': 85, 'value': 82},
    },
    {
        'id': 'drift',
        'name': 'Drift',
        'category': 'Business',
        'description': 'Conversational marketing platform',
        'url': 'https://www.drift.com',
        'pricing': 'Free + Paid',
        'score': 83,
        'developer': 'Drift',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 78, 'speed': 81, 'ease': 83, 'value': 80},
    },
    {
        'id': 'zendesk',
        'name': 'Zendesk',
        'category': 'Business',
        'description': 'Customer service platform with AI',
        'url': 'https://www.zendesk.com',
        'pricing': 'Free + Paid',
        'score': 84,
        'developer': 'Zendesk',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 79, 'speed': 82, 'ease': 84, 'value': 81},
    },
    {
        'id': 'freshdesk',
        'name': 'Freshdesk',
        'category': 'Business',
        'description': 'Cloud-based support ticket system',
        'url': 'https://freshdesk.com',
        'pricing': 'Free + Paid',
        'score': 82,
        'developer': 'Freshworks',
        'trending': False,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 77, 'speed': 80, 'ease': 82, 'value': 79},
    },
    {
        'id': 'helpscout',
        'name': 'Helpscout',
        'category': 'Business',
        'description': 'Help desk software with AI',
        'url': 'https://www.helpscout.com',
        'pricing': 'Free + Paid',
        'score': 81,
        'developer': 'Help Scout',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 76, 'speed': 79, 'ease': 81, 'value': 78},
    },
    {
        'id': 'buffer',
        'name': 'Buffer',
        'category': 'Business',
        'description': 'Social media scheduling with AI insights',
        'url': 'https://buffer.com',
        'pricing': 'Free + Paid',
        'score': 83,
        'developer': 'Buffer',
        'trending': False,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 78, 'speed': 81, 'ease': 83, 'value': 80},
    },
    {
        'id': 'hootsuite',
        'name': 'Hootsuite',
        'category': 'Business',
        'description': 'Social media management platform',
        'url': 'https://hootsuite.com',
        'pricing': 'Free + Paid',
        'score': 84,
        'developer': 'Hootsuite',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 79, 'speed': 82, 'ease': 84, 'value': 81},
    },
    {
        'id': 'sprout-social',
        'name': 'Sprout Social',
        'category': 'Business',
        'description': 'Social media management and analytics',
        'url': 'https://sproutsocial.com',
        'pricing': 'Free + Paid',
        'score': 85,
        'developer': 'Sprout Social',
        'trending': False,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 80, 'speed': 83, 'ease': 85, 'value': 82},
    },
    {
        'id': 'later',
        'name': 'Later',
        'category': 'Business',
        'description': 'Instagram marketing and scheduling',
        'url': 'https://www.later.com',
        'pricing': 'Free + Paid',
        'score': 82,
        'developer': 'Later',
        'trending': False,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 77, 'speed': 80, 'ease': 82, 'value': 79},
    },
    {
        'id': 'semrush',
        'name': 'Semrush',
        'category': 'Business',
        'description': 'SEO and content marketing platform',
        'url': 'https://semrush.com',
        'pricing': 'Free + Paid',
        'score': 86,
        'developer': 'Semrush',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 81, 'speed': 84, 'ease': 86, 'value': 83},
    },
    {
        'id': 'notion-ai',
        'name': 'Notion AI',
        'category': 'Business',
        'description': 'AI features in Notion workspace',
        'url': 'https://www.notion.so',
        'pricing': 'Free + Paid',
        'score': 84,
        'developer': 'Notion',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 79, 'speed': 82, 'ease': 84, 'value': 81},
    },
    {
        'id': 'obsidian-copilot',
        'name': 'Obsidian Copilot',
        'category': 'Business',
        'description': 'AI assistant for Obsidian notes',
        'url': 'https://obsidian.md',
        'pricing': 'Free + Paid',
        'score': 81,
        'developer': 'Obsidian',
        'trending': False,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 76, 'speed': 79, 'ease': 81, 'value': 78},
    },
    {
        'id': 'roam-research',
        'name': 'Roam Research',
        'category': 'Business',
        'description': 'Connected notes system with AI',
        'url': 'https://roamresearch.com',
        'pricing': 'Free + Paid',
        'score': 80,
        'developer': 'Roam',
        'trending': False,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 75, 'speed': 78, 'ease': 80, 'value': 77},
    },
    {
        'id': 'ms-copilot-365',
        'name': 'Microsoft Copilot in Microsoft 365',
        'category': 'Business',
        'description': 'AI assistant integrated in MS Office',
        'url': 'https://www.microsoft.com',
        'pricing': 'Free + Paid',
        'score': 88,
        'developer': 'Microsoft',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 83, 'speed': 86, 'ease': 88, 'value': 85},
    },
    {
        'id': 'google-workspace-ai',
        'name': 'Google Workspace AI',
        'category': 'Business',
        'description': 'AI features in Google Workspace',
        'url': 'https://workspace.google.com',
        'pricing': 'Free + Paid',
        'score': 86,
        'developer': 'Google',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 81, 'speed': 84, 'ease': 86, 'value': 83},
    },
    {
        'id': 'relatable',
        'name': 'Relatable',
        'category': 'Business',
        'description': 'AI product recommendation engine',
        'url': 'https://relatable.ai',
        'pricing': 'Free + Paid',
        'score': 79,
        'developer': 'Relatable',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 74, 'speed': 77, 'ease': 79, 'value': 76},
    },
    {
        'id': 'algopix',
        'name': 'Algopix',
        'category': 'Business',
        'description': 'Amazon seller analytics with AI',
        'url': 'https://www.algopix.com',
        'pricing': 'Free + Paid',
        'score': 81,
        'developer': 'Algopix',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 76, 'speed': 79, 'ease': 81, 'value': 78},
    },
    {
        'id': 'keepa',
        'name': 'Keepa',
        'category': 'Business',
        'description': 'Amazon price tracking and analytics',
        'url': 'https://keepa.com',
        'pricing': 'Free + Paid',
        'score': 82,
        'developer': 'Keepa',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 77, 'speed': 80, 'ease': 82, 'value': 79},
    },
    {
        'id': 'khan-academy',
        'name': 'Khan Academy',
        'category': 'Research',
        'description': 'Learning platform with AI personalization',
        'url': 'https://www.khanacademy.org',
        'pricing': 'Free + Paid',
        'score': 85,
        'developer': 'Khan Academy',
        'trending': False,
        'tags': ['ai', 'research', 'research', 'learning', 'education'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 80, 'speed': 83, 'ease': 85, 'value': 82},
    },
    {
        'id': 'duolingo-max',
        'name': 'Duolingo Max',
        'category': 'Research',
        'description': 'Language learning with AI',
        'url': 'https://www.duolingo.com',
        'pricing': 'Free + Paid',
        'score': 83,
        'developer': 'Duolingo',
        'trending': False,
        'tags': ['ai', 'research', 'research', 'learning', 'education'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 78, 'speed': 81, 'ease': 83, 'value': 80},
    },
    {
        'id': 'squirrel-ai',
        'name': 'Squirrel AI',
        'category': 'Research',
        'description': 'Adaptive learning platform',
        'url': 'https://www.squirrelai.com',
        'pricing': 'Free + Paid',
        'score': 82,
        'developer': 'Squirrel AI',
        'trending': True,
        'tags': ['ai', 'research', 'research', 'learning', 'education'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 77, 'speed': 80, 'ease': 82, 'value': 79},
    },
    {
        'id': 'coursera',
        'name': 'Coursera',
        'category': 'Research',
        'description': 'Online learning platform with AI',
        'url': 'https://www.coursera.org',
        'pricing': 'Free + Paid',
        'score': 84,
        'developer': 'Coursera',
        'trending': True,
        'tags': ['ai', 'research', 'research', 'learning', 'education'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 79, 'speed': 82, 'ease': 84, 'value': 81},
    },
    {
        'id': 'hireability',
        'name': 'HireAbility',
        'category': 'Business',
        'description': 'AI recruitment and hiring platform',
        'url': 'https://www.hireability.ai',
        'pricing': 'Free + Paid',
        'score': 80,
        'developer': 'HireAbility',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 75, 'speed': 78, 'ease': 80, 'value': 77},
    },
    {
        'id': 'workable',
        'name': 'Workable',
        'category': 'Business',
        'description': 'Recruitment software with AI',
        'url': 'https://www.workable.com',
        'pricing': 'Free + Paid',
        'score': 83,
        'developer': 'Workable',
        'trending': False,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 78, 'speed': 81, 'ease': 83, 'value': 80},
    },
    {
        'id': 'interviewer',
        'name': 'Interviewer',
        'category': 'Business',
        'description': 'AI video interviewing platform',
        'url': 'https://www.interviewer.ai',
        'pricing': 'Free + Paid',
        'score': 79,
        'developer': 'Interviewer',
        'trending': True,
        'tags': ['ai', 'business', 'business', 'analytics', 'productivity'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 74, 'speed': 77, 'ease': 79, 'value': 76},
    },
    {
        'id': 'github-copilot-x',
        'name': 'GitHub Copilot X',
        'category': 'Coding',
        'description': 'Advanced version of GitHub Copilot',
        'url': 'https://github.com/features/copilot',
        'pricing': 'Free + Paid',
        'score': 96,
        'developer': 'GitHub',
        'trending': False,
        'tags': ['ai', 'coding', 'code', 'development', 'programming'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 91, 'speed': 94, 'ease': 96, 'value': 93},
    },
    {
        'id': 'enzyme',
        'name': 'Enzyme',
        'category': 'Coding',
        'description': 'AI code review and quality tool',
        'url': 'https://getenzyme.com',
        'pricing': 'Free + Paid',
        'score': 83,
        'developer': 'Enzyme',
        'trending': True,
        'tags': ['ai', 'coding', 'code', 'development', 'programming'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 78, 'speed': 81, 'ease': 83, 'value': 80},
    },
    {
        'id': 'kolkoda',
        'name': 'Kolkoda',
        'category': 'Coding',
        'description': 'AI-powered code sharing platform',
        'url': 'https://kolkoda.ai',
        'pricing': 'Free + Paid',
        'score': 78,
        'developer': 'Kolkoda',
        'trending': True,
        'tags': ['ai', 'coding', 'code', 'development', 'programming'],
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
        'pros': ['Pro 1', 'Pro 2'],
        'cons': ['Con 1'],
        'lastUpdated': '2026-03-01',
        'userBase': '10K+ users',
        'scoreBreakdown': {'accuracy': 73, 'speed': 76, 'ease': 78, 'value': 75},
    },
]
